add: canto
neobase-one/splits-subgraph pull request #1
Opened 2022-11-27 07:24 UTC by jessepinkman9900

### Usage
- yarn prepare:canto
- graph create --node http://localhost:8020/ neobase/splits-subgraph
- graph deploy --node http://localhost:8020/ --ipfs http://localhost:5001 neobase/splits-subgraph

2022-11-28 11:44 UTC, akshatcx requested changes

2022-11-28 11:44 UTC, akshatcx commented on config/canto.json
> +  "splitStartBlock": "1775176",
fix indenting

2022-11-28 11:46 UTC, akshatcx commented
hmm, on second thought lets deploy off liquid staking and add it to subgraph as well

2022-11-29 05:08 UTC, jessepinkman9900 commented on config/canto.json
> +  "splitStartBlock": "1775176",
resolved

2022-12-05 18:28 UTC, akshatcx approved these changes

2022-12-05 18:29 UTC, merged